const employees = [
  {
    id: 1,
    first_name: "Felipe",
    last_name: "Manhood",
    email: "fmanhood0@reddit.com",
    gender: "Male",
    salary: "5782212.99",
    country: "China",
    department: "Product Management",
    rank: "Legal Assistant",
  },
  {
    id: 2,
    first_name: "Chick",
    last_name: "Petz",
    email: "cpetz1@gmpg.org",
    gender: "Male",
    salary: "5224912.22",
    country: "Colombia",
    department: "Support",
    rank: "Data Coordinator",
  },
  {
    id: 3,
    first_name: "Garv",
    last_name: "Haker",
    email: "ghaker2@time.com",
    gender: "Male",
    salary: "4352572.30",
    country: "China",
    department: "Legal",
    rank: "Product Engineer",
  },
  {
    id: 4,
    first_name: "Kaitlin",
    last_name: "Riccio",
    email: "kriccio3@unicef.org",
    gender: "Female",
    salary: "4984570.52",
    country: "United States",
    department: "Sales",
    rank: "Sales Representative",
  },
  {
    id: 5,
    first_name: "Vernice",
    last_name: "Abthorpe",
    email: "vabthorpe4@about.me",
    gender: "Female",
    salary: "607379.05",
    country: "Indonesia",
    department: "Business Development",
    rank: "Automation Specialist IV",
  },
  {
    id: 6,
    first_name: "Monte",
    last_name: "Brumble",
    email: "mbrumble5@usda.gov",
    gender: "Male",
    salary: "6324195.42",
    country: "Norway",
    department: "Research and Development",
    rank: "Developer I",
  },
  {
    id: 7,
    first_name: "Florance",
    last_name: "Burnand",
    email: "fburnand6@senate.gov",
    gender: "Female",
    salary: "5486647.10",
    country: "Russia",
    department: "Marketing",
    rank: "Senior Financial Analyst",
  },
  {
    id: 8,
    first_name: "Land",
    last_name: "Ancliff",
    email: "lancliff7@dyndns.org",
    gender: "Male",
    salary: "2358165.88",
    country: "Sweden",
    department: "Training",
    rank: "Teacher",
  },
  {
    id: 9,
    first_name: "Gerhardine",
    last_name: "Vanderplas",
    email: "gvanderplas8@merriam-webster.com",
    gender: "Female",
    salary: "4293715.75",
    country: "Macedonia",
    department: "Human Resources",
    rank: "Quality Control Specialist",
  },
  {
    id: 10,
    first_name: "Tamqrah",
    last_name: "McSkeagan",
    email: "tmcskeagan9@odnoklassniki.ru",
    gender: "Female",
    salary: "95902.44",
    country: "Cameroon",
    department: "Support",
    rank: "Paralegal",
  },
  {
    id: 11,
    first_name: "Tessy",
    last_name: "Pierce",
    email: "tpiercea@constantcontact.com",
    gender: "Female",
    salary: "790952.29",
    country: "Brazil",
    department: "Marketing",
    rank: "General Manager",
  },
  {
    id: 12,
    first_name: "Ninette",
    last_name: "Kenealy",
    email: "nkenealyb@angelfire.com",
    gender: "Female",
    salary: "1402833.09",
    country: "Indonesia",
    department: "Research and Development",
    rank: "Assistant Manager",
  },
  {
    id: 13,
    first_name: "Erin",
    last_name: "Brinkler",
    email: "ebrinklerc@live.com",
    gender: "Female",
    salary: "2349251.69",
    country: "China",
    department: "Support",
    rank: "Payment Adjustment Coordinator",
  },
  {
    id: 14,
    first_name: "Duke",
    last_name: "Giacubbo",
    email: "dgiacubbod@aboutads.info",
    gender: "Male",
    salary: "1931734.65",
    country: "Sweden",
    department: "Marketing",
    rank: "Environmental Specialist",
  },
  {
    id: 15,
    first_name: "Kattie",
    last_name: "Kofax",
    email: "kkofaxe@uiuc.edu",
    gender: "Female",
    salary: "1292137.59",
    country: "Argentina",
    department: "Marketing",
    rank: "Software Consultant",
  },
  {
    id: 16,
    first_name: "Anthea",
    last_name: "Arnholtz",
    email: "aarnholtzf@soup.io",
    gender: "Female",
    salary: "850813.10",
    country: "Indonesia",
    department: "Human Resources",
    rank: "Paralegal",
  },
  {
    id: 17,
    first_name: "Debi",
    last_name: "Bernardoux",
    email: "dbernardouxg@nba.com",
    gender: "Female",
    salary: "1802258.44",
    country: "Greece",
    department: "Engineering",
    rank: "Marketing Manager",
  },
  {
    id: 18,
    first_name: "Denna",
    last_name: "Tonkes",
    email: "dtonkesh@comcast.net",
    gender: "Female",
    salary: "3386720.80",
    country: "Indonesia",
    department: "Support",
    rank: "Cost Accountant",
  },
  {
    id: 19,
    first_name: "Crystal",
    last_name: "Sangwine",
    email: "csangwinei@vimeo.com",
    gender: "Female",
    salary: "6010434.96",
    country: "Philippines",
    department: "Human Resources",
    rank: "Database Administrator IV",
  },
  {
    id: 20,
    first_name: "Letitia",
    last_name: "Philpots",
    email: "lphilpotsj@apache.org",
    gender: "Female",
    salary: "2640531.37",
    country: "Portugal",
    department: "Training",
    rank: "Structural Engineer",
  },
  {
    id: 21,
    first_name: "Edlin",
    last_name: "Linstead",
    email: "elinsteadk@furl.net",
    gender: "Male",
    salary: "1524181.71",
    country: "Indonesia",
    department: "Support",
    rank: "Research Assistant I",
  },
  {
    id: 22,
    first_name: "Ezra",
    last_name: "Farmloe",
    email: "efarmloel@google.fr",
    gender: "Male",
    salary: "3196077.93",
    country: "China",
    department: "Human Resources",
    rank: "Help Desk Technician",
  },
  {
    id: 23,
    first_name: "Cybil",
    last_name: "Safhill",
    email: "csafhillm@studiopress.com",
    gender: "Female",
    salary: "6646332.48",
    country: "Colombia",
    department: "Research and Development",
    rank: "Accountant IV",
  },
  {
    id: 24,
    first_name: "Ritchie",
    last_name: "Giacomuzzi",
    email: "rgiacomuzzin@mozilla.com",
    gender: "Male",
    salary: "3435369.35",
    country: "Japan",
    department: "Services",
    rank: "Mechanical Systems Engineer",
  },
  {
    id: 25,
    first_name: "Nichols",
    last_name: "Iacobo",
    email: "niacoboo@globo.com",
    gender: "Male",
    salary: "6057282.11",
    country: "Panama",
    department: "Sales",
    rank: "Staff Scientist",
  },
];

// const employees2 = employees.map((employee,index)=>employee.salary[index] = parseFloat(employee.salary));
// console.log(employees2);

//total salary
const totalSalary = employees.reduce(
  (acc, employee) => acc + parseFloat(employee.salary),
  0
);
console.log(`Total sdalary ${totalSalary.toFixed(2)}`);

//what is average salary of female employees;
let totalFemale = employees.filter((employee) => employee.gender === "Female");


const totalFemaleSalary = employees
  .filter((employee) => employee.gender === "Female")
  .reduce((acc, employee) => acc + parseFloat(employee.salary), 0);

  let averageSalary = totalFemaleSalary / totalFemale.length;

console.log("female salary: " + averageSalary.toFixed(2));
